

IMBALANCED_TRAIN_SIZE = 269695
IMBALANCED_VAL__SIZE  = 123723
IMBALANCED_TEST_SIZE = 125866

BALANCED_TRAIN_SIZE = 13932
BALANCED_VAL_SIZE = 6606
# BALANCED_TEST_SIZE = 6604

DOWNSAMPLED_TRAIN_SIZE = 69660
DOWNSAMPLED_VAL_SIZE = 33030

BALANCED_VY_TRAIN_SIZE = 9790
BALANCED_VY_VAL_SIZE = 4758
# BALANCED_VY_TEST_SIZE = 4500

BALANCED_TRAINING_FILENAMES = 'balanced_train-part-*.tfrecord'
BALANCED_VALIDATION_FILENAMES = 'balanced_val-part-*.tfrecord'
BALANCED_TEST_FILENAMES = 'balanced_test-part-*.tfrecord'

DOWNSAMPLED_TRAINING_FILENAMES = 'balanced_10_90_train-part-*.tfrecord'
DOWNSAMPLED_VALIDATION_FILENAMES = 'balanced_10_90_val-part-*.tfrecord'
DOWNSAMPLED_TEST_FILENAMES = 'balanced_10_90_test-part-*.tfrecord'

IMBALANCED_TRAINING_FILENAMES = 'train-part-*.tfrecord'
IMBALANCED_VALIDATION_FILENAMES = 'val-part-*.tfrecord'
IMBALANCED_TEST_FILENAMES = 'test-part-*.tfrecord'